// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwT5YRsf_hBQqNKASrdDKdRDHYjKh9RrM',
    appId: '1:801356952341:web:fcbca957b20bf1d39cef1c',
    messagingSenderId: '801356952341',
    projectId: 'sayhi-2e08b',
    authDomain: 'sayhi-2e08b.firebaseapp.com',
    storageBucket: 'sayhi-2e08b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirqFTzsPvNUYO7ZiTFbqOKnffN3rPBZY',
    appId: '1:801356952341:android:8062e0878021582c9cef1c',
    messagingSenderId: '801356952341',
    projectId: 'sayhi-2e08b',
    storageBucket: 'sayhi-2e08b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQEMNi2ewsce8xIjs7Zwz5KbAx518Eu2o',
    appId: '1:801356952341:ios:a4cdda92da5c93ef9cef1c',
    messagingSenderId: '801356952341',
    projectId: 'sayhi-2e08b',
    storageBucket: 'sayhi-2e08b.appspot.com',
    iosClientId: '801356952341-v3sodgf0ltmjdai94p945bvmjpnqrvq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sayhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQEMNi2ewsce8xIjs7Zwz5KbAx518Eu2o',
    appId: '1:801356952341:ios:a4cdda92da5c93ef9cef1c',
    messagingSenderId: '801356952341',
    projectId: 'sayhi-2e08b',
    storageBucket: 'sayhi-2e08b.appspot.com',
    iosClientId: '801356952341-v3sodgf0ltmjdai94p945bvmjpnqrvq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sayhi',
  );
}
